import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  header: {
    backgroundColor: "#FDB813",
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  titulo: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginBottom: 5,
  },
  subtitulo: { fontSize: 16, color: "#4A4A4A" },
  formulario: {
    backgroundColor: "#FFFFFF",
    margin: 15,
    padding: 20,
    borderRadius: 12,
    elevation: 3,
  },
  labelFormulario: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C2C2C",
    marginBottom: 15,
  },
  input: {
    backgroundColor: "#F5F5F5",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 12,
    color: "#1A1A1A",
  },
  boton: {
    backgroundColor: "#FDB813",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  botonDeshabilitado: { backgroundColor: "#FFD54F", opacity: 0.7 },
  botonCargando: { flexDirection: "row", alignItems: "center" },
  textoBotonCargando: {
    marginLeft: 10,
    color: "#1A1A1A",
    fontSize: 16,
    fontWeight: "600",
  },
  textoBoton: { color: "#1A1A1A", fontSize: 18, fontWeight: "bold" },
  contenedorLista: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    margin: 15,
    marginTop: 0,
    borderRadius: 12,
    elevation: 3,
  },
  headerLista: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    flexWrap: "wrap",
  },
  tituloLista: { fontSize: 20, fontWeight: "bold", color: "#2C2C2C" },
  filtroContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
  },
  textoFiltro: { fontSize: 14, color: "#4A4A4A", marginRight: 8 },
  textoRecargar: { fontSize: 14, color: "#FDB813", fontWeight: "600" },
  tarjetaContacto: { flexDirection: "row", padding: 15, alignItems: "center" },
  avatarContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFF9C4",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  avatar: { fontSize: 24, fontWeight: "bold", color: "#1A1A1A" },
  infoContacto: { flex: 1 },
  nombreContacto: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  telefonoContacto: { fontSize: 14, color: "#4A4A4A", marginBottom: 2 },
  emailContacto: { fontSize: 14, color: "#666" },
  separador: { height: 1, backgroundColor: "#F0F0F0", marginLeft: 80 },
  centrado: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  textoCargando: { marginTop: 10, fontSize: 16, color: "#4A4A4A" },
  textoVacio: { fontSize: 48, marginBottom: 10, textAlign: "center" },
  textoVacio2: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2C2C2C",
    textAlign: "center",
  },
  subtextoVacio: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginTop: 5,
  },
});
